apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: lphg5i23p-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:b80d7dda20b26d0c0d9bbf2a227c956b6f5bd7b6@sha256:a61029e42a2ac2650c30bf23ca67245f6ee80c8508a301653cf073fc57a9efcc
          name: container-image
