apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lphg5i23p-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lphg5i23p-go 
  name: lphg5i23p-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lphg5i23p-go 
